"""Import a SCIP index into platform semantic evidence (design 9 and 10.2).

``import_scip`` turns the bytes an indexer produced into a ``SemanticIndex``:
the run metadata, documents with their definitions and references, symbol
information (documentation, kind, signature, relationships) and external
symbols. It parses the official SCIP protobuf in process (bindings generated by
``scripts/generate-scip-bindings.sh``) and never shells out.

The bytes are untrusted. The importer

- bounds the total size before parsing, then the document, occurrence, symbol,
  relationship, tool-argument and symbol-length counts, and fails closed with a
  typed, content-free ``ScipImportError``. A linear wire-format pre-scan counts
  and caps documents, external symbols, occurrences and symbols before any of
  them is parsed, and each ``Document`` is then parsed on its own, so a flood of
  tiny messages is refused without being materialized (see ``ScipLimits``);
- never fabricates an edge: an invalid range (negative, start after end, wrong
  arity, outside the document when the text is known), an empty or malformed
  symbol, or a document with an unsafe path is discarded and reported as an
  ``ImportDiagnostic`` that echoes no index content;
- never treats ``Metadata.project_root`` as a filesystem path: only its last
  segment is kept, as a label.

Symbol identity comes from ``identity.symbol_logical_id``: a global SCIP symbol
is the identity exactly as SCIP spells it, and a ``local N`` symbol uses the
per-file fallback. The importer cannot read Git history, so it cannot derive a
file logical ID (that needs the introducing commit, see ``identity``); the
indexer passes ``file_logical_ids`` per path. Without one, a document's local
symbols are discarded with a diagnostic rather than tied to a made-up file.

SCIP evidence is direct, so its confidence is 1.0 and it outranks Tree-sitter
and inference (``evidence_outranks``, used by PLATFORM-037 to merge claims).
"""

from __future__ import annotations

import hashlib
import re
import uuid
from collections.abc import Iterator, Mapping
from dataclasses import dataclass
from typing import Final, Literal

from google.protobuf.message import DecodeError, Message

from agent_context_platform.indexing.identity import (
    EvidenceKind,
    encode_components,
    repository_namespace,
    symbol_logical_id,
    symbol_revision_id,
)
from agent_context_platform.indexing.scanner import is_safe_repo_path
from agent_context_platform.indexing.scip_pb import scip_pb2

# Direct claims (design 9.3) carry full confidence.
SCIP_CONFIDENCE: Final = 1.0

# Ascending precedence among the semantic code evidence kinds: SCIP wins over
# Tree-sitter, which wins over agent or LLM inference. Git, test and user
# evidence answer other questions and are not ranked here.
SEMANTIC_EVIDENCE_ORDER: Final = ("llm_inference", "agent", "tree_sitter", "scip")

_OID = re.compile(r"(?:[0-9a-f]{40}|[0-9a-f]{64})")
_LOCAL_ID = re.compile(r"[A-Za-z0-9_+\-$]+")
_NO_FILE: Final = uuid.UUID(int=0)  # unused by identity for global symbols
_MAX_LABEL_LENGTH: Final = 256
_MAX_PATH_BYTES: Final = 4096
_UNKNOWN_KIND: Final = "unknown"

type ImportErrorReason = Literal[
    "index_too_large",
    "malformed",
    "missing_metadata",
    "tool_info_too_large",
    "too_many_documents",
    "too_many_external_symbols",
    "too_many_occurrences",
    "too_many_symbols",
    "too_many_relationships",
    "too_many_repeated_items",
    "symbol_too_long",
]
type DiagnosticCode = Literal[
    "duplicate_document",
    "invalid_range",
    "invalid_roles",
    "invalid_symbol",
    "local_symbol_without_file_identity",
    "out_of_document_range",
    "unsafe_path",
]
type RelationshipKind = Literal["reference", "implementation", "type_definition", "definition"]


class ScipImportError(Exception):
    """The index is unusable; ``reason`` is a stable code and never contains index content."""

    def __init__(self, reason: ImportErrorReason) -> None:
        super().__init__(reason)
        self.reason: ImportErrorReason = reason


@dataclass(frozen=True, slots=True)
class ScipLimits:
    """Upper bounds applied to untrusted index bytes."""

    # Worst-case memory. A Python protobuf message costs on the order of 0.5 KB while an
    # empty one is 2 bytes on the wire (a 250x expansion), so no count of messages is
    # ever materialized before the wire pre-scan has bounded it. What stays alive is one
    # Document at a time plus the result: roughly 1 KB per kept occurrence or symbol, so
    # the totals below bound the result near 2 GB and the byte cap bounds pre-scan input.
    max_index_bytes: int = 64 * 1024 * 1024
    max_documents: int = 100_000
    max_occurrences_per_document: int = 500_000
    max_symbols_per_document: int = 100_000
    max_total_occurrences: int = 2_000_000
    max_total_symbols: int = 1_000_000
    max_repeated_items_per_message: int = 1_000
    max_external_symbols: int = 500_000
    max_relationships_per_symbol: int = 10_000
    max_symbol_length: int = 4096
    max_tool_arguments: int = 256
    max_tool_field_length: int = 4096


DEFAULT_LIMITS: Final = ScipLimits()


@dataclass(frozen=True, slots=True)
class SourceRange:
    """A zero-based range; ``end_character`` is exclusive, in the document's position encoding."""

    start_line: int
    start_character: int
    end_line: int
    end_character: int


@dataclass(frozen=True, slots=True)
class SemanticOccurrence:
    """A definition or reference of ``symbol`` at ``range``."""

    symbol: str
    symbol_id: uuid.UUID
    range: SourceRange
    enclosing_range: SourceRange | None
    roles: int
    is_definition: bool
    override_documentation: tuple[str, ...]
    evidence_kind: EvidenceKind = "scip"
    confidence: float = SCIP_CONFIDENCE


@dataclass(frozen=True, slots=True)
class SemanticRelationship:
    """A SCIP relationship between two symbols (implementation, type definition, ...)."""

    source_symbol: str
    source_id: uuid.UUID
    target_symbol: str
    target_id: uuid.UUID
    kinds: tuple[RelationshipKind, ...]
    evidence_kind: EvidenceKind = "scip"
    confidence: float = SCIP_CONFIDENCE


@dataclass(frozen=True, slots=True)
class SemanticSymbol:
    """Symbol information from a document (``document_path``) or the external symbols."""

    symbol: str
    symbol_id: uuid.UUID
    revision_id: uuid.UUID
    document_path: str | None
    kind: str
    display_name: str
    documentation: tuple[str, ...]
    signature_text: str
    relationships: tuple[SemanticRelationship, ...]


@dataclass(frozen=True, slots=True)
class SemanticDocument:
    """A kept document: only safe paths, valid ranges and identifiable symbols remain."""

    path: str
    language: str
    position_encoding: str
    file_logical_id: uuid.UUID | None
    occurrences: tuple[SemanticOccurrence, ...]
    symbols: tuple[SemanticSymbol, ...]


@dataclass(frozen=True, slots=True)
class ImportDiagnostic:
    """A discarded item. ``path`` is None for an unsafe path; nothing else is echoed."""

    code: DiagnosticCode
    path: str | None
    occurrence_index: int | None = None


@dataclass(frozen=True, slots=True)
class IndexRun:
    """How the index was produced (design 10.2: indexer, version and toolchain are recorded).

    SCIP itself carries no toolchain, so it is caller input. ``tool_arguments`` are
    recorded as the indexer reported them; the event pipeline redacts them.
    ``project_root_name`` is a label, not a path.
    """

    tool_name: str
    tool_version: str
    tool_arguments: tuple[str, ...]
    toolchain: str | None
    commit: str
    project_root_name: str
    text_encoding: str


@dataclass(frozen=True, slots=True)
class SemanticIndex:
    """Semantic evidence of one indexer run at one commit."""

    repository_id: str
    commit: str
    run: IndexRun
    documents: tuple[SemanticDocument, ...]
    external_symbols: tuple[SemanticSymbol, ...]
    diagnostics: tuple[ImportDiagnostic, ...]


def evidence_outranks(
    kind: str, confidence: float, other_kind: str, other_confidence: float
) -> bool:
    """Whether a claim beats a conflicting one: evidence kind first, then confidence.

    SCIP outranks Tree-sitter outranks agent and LLM inference, even when the
    weaker kind reports a higher number, because their confidences are not
    comparable. Within one kind the higher confidence wins; a tie is not
    outranked. Kinds outside the semantic set (git, test, user) raise
    ``ValueError``.
    """
    for value in (confidence, other_confidence):
        if not 0 <= value <= 1:
            raise ValueError("confidence must be in [0, 1]")
    rank, other_rank = _rank(kind), _rank(other_kind)
    if rank != other_rank:
        return rank > other_rank
    return confidence > other_confidence


def _rank(kind: str) -> int:
    try:
        return SEMANTIC_EVIDENCE_ORDER.index(kind)
    except ValueError:
        raise ValueError("unsupported evidence kind for semantic ranking") from None


def import_scip(
    index_bytes: bytes,
    repository_id: str,
    commit: str,
    *,
    toolchain: str | None = None,
    file_logical_ids: Mapping[str, uuid.UUID] | None = None,
    sources: Mapping[str, str] | None = None,
    limits: ScipLimits = DEFAULT_LIMITS,
) -> SemanticIndex:
    """Import ``index_bytes``, an untrusted SCIP index of ``commit`` in ``repository_id``.

    ``toolchain`` records the runtime the indexer ran on. ``file_logical_ids`` maps
    a document path to its file logical ID (see the module docstring). ``sources``
    maps a path to its text so ranges can be checked against the real file;
    otherwise ``Document.text`` is used when present, and without text only the
    structure of a range is checked. Raises ``ScipImportError`` for an unusable
    index and ``ValueError`` for a bad ``repository_id`` or ``commit``.
    """
    repository_namespace(repository_id)
    if not _OID.fullmatch(commit):
        raise ValueError("commit must be a lowercase 40 or 64 character hex object id")
    if len(index_bytes) > limits.max_index_bytes:
        raise ScipImportError("index_too_large")
    # Pre-scan the wire format and cap every repeated message count before any message
    # is materialized; a full ParseFromString would build them all first.
    index = scip_pb2.Index()
    document_slices: list[tuple[int, int]] = []
    external_slices: list[tuple[int, int]] = []
    for number, start, stop in _walk(index_bytes, 0, len(index_bytes)):
        if number == 1:
            _merge_metadata(index, index_bytes[start:stop], limits)
        elif number == 2:
            document_slices.append((start, stop))
            if len(document_slices) > limits.max_documents:
                raise ScipImportError("too_many_documents")
        elif number == 3:
            external_slices.append((start, stop))
            if len(external_slices) > limits.max_external_symbols:
                raise ScipImportError("too_many_external_symbols")
    run = _run(index, commit, toolchain, limits)

    importer = _Importer(repository_id, limits, file_logical_ids or {}, sources or {})
    documents: list[SemanticDocument] = []
    seen: set[str] = set()
    total_occurrences = total_symbols = 0
    for start, stop in document_slices:
        chunk = index_bytes[start:stop]
        occurrence_count, symbol_count = _prescan_document(chunk, limits)
        total_occurrences += occurrence_count
        total_symbols += symbol_count
        if total_occurrences > limits.max_total_occurrences:
            raise ScipImportError("too_many_occurrences")
        if total_symbols > limits.max_total_symbols:
            raise ScipImportError("too_many_symbols")
        document = _parse(scip_pb2.Document, chunk)
        path = document.relative_path
        if len(path.encode("utf-8")) > _MAX_PATH_BYTES or not is_safe_repo_path(path):
            importer.diagnose("unsafe_path", None)
            continue
        if path in seen:
            importer.diagnose("duplicate_document", path)
            continue
        seen.add(path)
        documents.append(importer.document(document))
    external_infos = (
        _parse_symbol_information(index_bytes[start:stop], limits)
        for start, stop in external_slices
    )
    external = tuple(
        symbol for info in external_infos if (symbol := importer.symbol(info, None, "", None))
    )
    return SemanticIndex(
        repository_id=repository_id,
        commit=commit,
        run=run,
        documents=tuple(documents),
        external_symbols=external,
        diagnostics=tuple(importer.diagnostics),
    )


def _varint(data: bytes, position: int, end: int) -> tuple[int, int]:
    value = 0
    for shift in range(0, 70, 7):
        if position >= end:
            raise ScipImportError("malformed")
        byte = data[position]
        position += 1
        value |= (byte & 0x7F) << shift
        if not byte & 0x80:
            return value, position
    raise ScipImportError("malformed")


def _walk(data: bytes, start: int, end: int) -> Iterator[tuple[int, int, int]]:
    """Yield ``(field number, payload start, payload stop)`` of each length-delimited field.

    A linear walk of the top-level wire format of ``data[start:end]`` that skips the
    other wire types and allocates nothing per field. Groups, a field number of zero
    and any overrun raise ``ScipImportError("malformed")``.
    """
    position = start
    while position < end:
        key, position = _varint(data, position, end)
        number, wire_type = key >> 3, key & 7
        if number == 0:
            raise ScipImportError("malformed")
        if wire_type == 0:
            _, position = _varint(data, position, end)
        elif wire_type == 1:
            position += 8
        elif wire_type == 5:
            position += 4
        elif wire_type == 2:
            length, position = _varint(data, position, end)
            if position + length > end:
                raise ScipImportError("malformed")
            yield number, position, position + length
            position += length
        else:
            raise ScipImportError("malformed")
        if position > end:
            raise ScipImportError("malformed")


def _parse[T: Message](message_type: type[T], data: bytes) -> T:
    try:
        return message_type.FromString(data)
    except DecodeError:
        raise ScipImportError("malformed") from None


def _count_children(data: bytes, field: int, cap: int, reason: ImportErrorReason) -> int:
    count = 0
    for number, _, _ in _walk(data, 0, len(data)):
        if number == field:
            count += 1
            if count > cap:
                raise ScipImportError(reason)
    return count


def _merge_metadata(index: scip_pb2.Index, data: bytes, limits: ScipLimits) -> None:
    for number, start, stop in _walk(data, 0, len(data)):
        if number == 2:  # tool_info
            _count_children(data[start:stop], 3, limits.max_tool_arguments, "tool_info_too_large")
    index.metadata.SetInParent()
    try:
        index.metadata.MergeFromString(data)
    except DecodeError:
        raise ScipImportError("malformed") from None


def _prescan_document(data: bytes, limits: ScipLimits) -> tuple[int, int]:
    """Count a document's occurrences and symbols, bounding nested repeats, before parsing."""
    occurrences = symbols = 0
    nested = limits.max_repeated_items_per_message
    occurrence_caps, symbol_caps = _occurrence_caps(limits), _symbol_caps(limits)
    for number, start, stop in _walk(data, 0, len(data)):
        if number == 2:
            occurrences += 1
            if occurrences > limits.max_occurrences_per_document:
                raise ScipImportError("too_many_occurrences")
            # A message with more than ``nested`` children is at least 2 * nested bytes.
            if stop - start > 2 * nested:
                _bound_repeats(data[start:stop], occurrence_caps)
        elif number == 3:
            symbols += 1
            if symbols > limits.max_symbols_per_document:
                raise ScipImportError("too_many_symbols")
            if stop - start > 2 * min(nested, limits.max_relationships_per_symbol):
                _bound_repeats(data[start:stop], symbol_caps)
    return occurrences, symbols


def _bound_repeats(data: bytes, caps: Mapping[int, tuple[int, ImportErrorReason]]) -> None:
    """Refuse a message whose listed repeated fields exceed their ``(cap, reason)``."""
    counts: dict[int, int] = {}
    for number, _, _ in _walk(data, 0, len(data)):
        if number in caps:
            counts[number] = counts.get(number, 0) + 1
            if counts[number] > caps[number][0]:
                raise ScipImportError(caps[number][1])


def _occurrence_caps(limits: ScipLimits) -> dict[int, tuple[int, ImportErrorReason]]:
    cap = limits.max_repeated_items_per_message
    # override_documentation (4) and diagnostics (6)
    return {4: (cap, "too_many_repeated_items"), 6: (cap, "too_many_repeated_items")}


def _symbol_caps(limits: ScipLimits) -> dict[int, tuple[int, ImportErrorReason]]:
    # documentation (3) and relationships (4)
    return {
        3: (limits.max_repeated_items_per_message, "too_many_repeated_items"),
        4: (limits.max_relationships_per_symbol, "too_many_relationships"),
    }


def _parse_symbol_information(data: bytes, limits: ScipLimits) -> scip_pb2.SymbolInformation:
    _bound_repeats(data, _symbol_caps(limits))
    return _parse(scip_pb2.SymbolInformation, data)


def _run(index: scip_pb2.Index, commit: str, toolchain: str | None, limits: ScipLimits) -> IndexRun:
    if not index.HasField("metadata") or not index.metadata.HasField("tool_info"):
        raise ScipImportError("missing_metadata")
    tool = index.metadata.tool_info
    if len(tool.arguments) > limits.max_tool_arguments:
        raise ScipImportError("tool_info_too_large")
    fields = (tool.name, tool.version, *tool.arguments)
    if any(len(value) > limits.max_tool_field_length for value in fields):
        raise ScipImportError("tool_info_too_large")
    if not tool.name:
        raise ScipImportError("missing_metadata")
    return IndexRun(
        tool_name=tool.name,
        tool_version=tool.version,
        tool_arguments=tuple(tool.arguments),
        toolchain=toolchain,
        commit=commit,
        project_root_name=_root_label(index.metadata.project_root),
        text_encoding=scip_pb2.TextEncoding.Name(index.metadata.text_document_encoding)
        if index.metadata.text_document_encoding in scip_pb2.TextEncoding.values()
        else _UNKNOWN_KIND,
    )


def _root_label(project_root: str) -> str:
    """The last segment of ``project_root`` as an inert label; the path itself is dropped."""
    label = project_root.rstrip("/").rsplit("/", 1)[-1]
    if len(label) > _MAX_LABEL_LENGTH or any(ord(c) < 32 or ord(c) == 127 for c in label):
        return ""
    return label


def _digest(*components: str) -> str:
    return hashlib.sha256(encode_components(*components).encode("utf-8")).hexdigest()


class _Importer:
    def __init__(
        self,
        repository_id: str,
        limits: ScipLimits,
        file_ids: Mapping[str, uuid.UUID],
        sources: Mapping[str, str],
    ) -> None:
        self._repository_id = repository_id
        self._limits = limits
        self._file_ids = file_ids
        self._sources = sources
        self.diagnostics: list[ImportDiagnostic] = []
        # The one resolver of local fallback IDs: kinds declared by the current document.
        self._declared_kinds: dict[str, str] = {}
        self._ids: dict[tuple[str, uuid.UUID | None, str], uuid.UUID] = {}

    def diagnose(self, code: DiagnosticCode, path: str | None, index: int | None = None) -> None:
        self.diagnostics.append(ImportDiagnostic(code, path, index))

    def document(self, document: scip_pb2.Document) -> SemanticDocument:
        limits, path = self._limits, document.relative_path
        if len(document.occurrences) > limits.max_occurrences_per_document:
            raise ScipImportError("too_many_occurrences")
        if len(document.symbols) > limits.max_symbols_per_document:
            raise ScipImportError("too_many_symbols")
        file_id = self._file_ids.get(path)
        self._declared_kinds = {info.symbol: _kind_name(info) for info in document.symbols}
        # Only a caller-supplied source or non-empty Document.text is known text; proto3
        # cannot tell an absent Document.text from an empty one.
        text = self._sources.get(path, document.text or None)
        bounds = _Bounds(text, document.position_encoding)
        occurrences: list[SemanticOccurrence] = []
        for position, occurrence in enumerate(document.occurrences):
            item = self._occurrence(occurrence, position, path, document, file_id, bounds)
            if item is not None:
                occurrences.append(item)
        symbols = tuple(
            symbol
            for info in document.symbols
            if (symbol := self.symbol(info, path, document.language, file_id)) is not None
        )
        return SemanticDocument(
            path=path,
            language=document.language,
            position_encoding=_enum_name(scip_pb2.PositionEncoding, document.position_encoding),
            file_logical_id=file_id,
            occurrences=tuple(occurrences),
            symbols=symbols,
        )

    def _occurrence(
        self,
        occurrence: scip_pb2.Occurrence,
        position: int,
        path: str,
        document: scip_pb2.Document,
        file_id: uuid.UUID | None,
        bounds: _Bounds,
    ) -> SemanticOccurrence | None:
        located = _range(occurrence)
        if located is None:
            self.diagnose("invalid_range", path, position)
            return None
        if not bounds.contains(located):
            self.diagnose("out_of_document_range", path, position)
            return None
        enclosing = _enclosing_range(occurrence)
        if _has_enclosing(occurrence):
            # The enclosing range must be valid, inside the document and contain the
            # occurrence; otherwise only it is dropped, the occurrence stays.
            if enclosing is None or not _encloses(enclosing, located):
                self.diagnose("invalid_range", path, position)
                enclosing = None
            elif not bounds.contains(enclosing):
                self.diagnose("out_of_document_range", path, position)
                enclosing = None
        if occurrence.symbol_roles < 0:
            self.diagnose("invalid_roles", path, position)
            return None
        symbol_id = self._identify(
            occurrence.symbol,
            document.language,
            file_id,
            path,
            position,
        )
        if symbol_id is None:
            return None
        return SemanticOccurrence(
            symbol=occurrence.symbol,
            symbol_id=symbol_id,
            range=located,
            enclosing_range=enclosing,
            roles=occurrence.symbol_roles,
            is_definition=bool(occurrence.symbol_roles & scip_pb2.Definition),
            override_documentation=tuple(occurrence.override_documentation),
        )

    def _identify(
        self,
        symbol: str,
        language: str,
        file_id: uuid.UUID | None,
        path: str | None,
        position: int | None,
    ) -> uuid.UUID | None:
        """Logical ID of ``symbol``, or None (with a diagnostic) when it cannot be identified."""
        if len(symbol.encode("utf-8")) > self._limits.max_symbol_length:
            raise ScipImportError("symbol_too_long")
        if not is_valid_symbol(symbol):
            self.diagnose("invalid_symbol", path, position)
            return None
        kind = self._declared_kinds.get(symbol, _UNKNOWN_KIND)
        if symbol.startswith("local ") and file_id is None:
            if path is None:  # external symbols are global by definition
                self.diagnose("invalid_symbol", path, position)
            else:
                self.diagnose("local_symbol_without_file_identity", path, position)
            return None
        key = (symbol, file_id if symbol.startswith("local ") else None, kind)
        found = self._ids.get(key)
        if found is None:
            found = self._ids[key] = symbol_logical_id(
                self._repository_id,
                scip_symbol=symbol,
                language=language,
                file_logical_id=file_id or _NO_FILE,
                qualified_name=symbol,
                kind=kind,
            )
        return found

    def symbol(
        self,
        info: scip_pb2.SymbolInformation,
        path: str | None,
        language: str,
        file_id: uuid.UUID | None,
    ) -> SemanticSymbol | None:
        if len(info.relationships) > self._limits.max_relationships_per_symbol:
            raise ScipImportError("too_many_relationships")
        kind = _kind_name(info)
        symbol_id = self._identify(info.symbol, language, file_id, path, None)
        if symbol_id is None:
            return None
        relationships: list[SemanticRelationship] = []
        for related in info.relationships:
            target_id = self._identify(related.symbol, language, file_id, path, None)
            if target_id is None:
                continue
            kinds = _relationship_kinds(related)
            relationships.append(
                SemanticRelationship(info.symbol, symbol_id, related.symbol, target_id, kinds)
            )
        signature_language, signature_text = _signature(info)
        signature_digest = _digest(
            "scip-signature-v1", kind, info.display_name, signature_language, signature_text
        )
        # SCIP has no body or AST; the semantic content it does carry is documentation
        # and relationships, so those are what a semantic revision hashes.
        semantic_digest = _digest(
            "scip-semantic-v1",
            *info.documentation,
            "relationships",
            *sorted(encode_components(r.target_symbol, *r.kinds) for r in relationships),
        )
        return SemanticSymbol(
            symbol=info.symbol,
            symbol_id=symbol_id,
            revision_id=symbol_revision_id(
                self._repository_id, symbol_id, signature_digest, semantic_digest
            ),
            document_path=path,
            kind=kind,
            display_name=info.display_name,
            documentation=tuple(info.documentation),
            signature_text=signature_text,
            relationships=tuple(relationships),
        )


def _signature(info: scip_pb2.SymbolInformation) -> tuple[str, str]:
    # The generated stub types this field as an unresolved nested name; it is a Document.
    signature = info.signature_documentation
    return str(signature.language), str(signature.text)  # type: ignore[attr-defined]


_IDENT_CHARS: Final = frozenset(
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_+-$"
)
_SUFFIXES: Final = frozenset("/#.:!")


def is_valid_symbol(symbol: str) -> bool:
    """Whether ``symbol`` follows the SCIP symbol grammar of the vendored ``scip.proto``.

    ``local <simple-identifier>``, or ``<scheme> <manager> <name> <version>
    <descriptor>+`` where a space inside a field is written as two spaces.
    Single left-to-right pass, so time is linear in the length and input cannot
    force backtracking.
    """
    if not symbol or any(ord(c) < 32 or ord(c) == 127 for c in symbol):
        return False
    if symbol.startswith("local "):
        return _LOCAL_ID.fullmatch(symbol, len("local ")) is not None
    position = 0
    for field in range(4):  # scheme, manager, package name, version
        start = position
        while position < len(symbol):
            if symbol[position] != " ":
                position += 1
            elif symbol.startswith("  ", position):
                position += 2
            else:
                break
        if position == start or position >= len(symbol):
            return False
        if field == 0 and symbol.startswith("local", start):
            return False
        position += 1  # the single separating space
    return _valid_descriptors(symbol, position)


def _name_end(symbol: str, position: int) -> int:
    """End of an identifier at ``position`` (simple or backtick-escaped), or -1."""
    size = len(symbol)
    if position < size and symbol[position] == "`":
        position += 1
        start = position
        while position < size:
            if symbol[position] == "`":
                if symbol.startswith("``", position):
                    position += 2
                    continue
                return position + 1 if position > start else -1
            position += 1
        return -1
    start = position
    while position < size and symbol[position] in _IDENT_CHARS:
        position += 1
    return position if position > start else -1


def _valid_descriptors(symbol: str, position: int) -> bool:
    size = len(symbol)
    if position >= size:
        return False
    while position < size:
        opener = symbol[position]
        if opener in "([":
            end = _name_end(symbol, position + 1)
            if end < 0 or end >= size or symbol[end] != (")" if opener == "(" else "]"):
                return False
            position = end + 1
            continue
        end = _name_end(symbol, position)
        if end < 0 or end >= size:
            return False
        if symbol[end] in _SUFFIXES:
            position = end + 1
        elif symbol[end] == "(":  # method: (<disambiguator>?).
            close = end + 1
            while close < size and symbol[close] in _IDENT_CHARS:
                close += 1
            if not symbol.startswith(").", close):
                return False
            position = close + 2
        else:
            return False
    return True


def _enum_name(enum: object, value: int) -> str:
    try:
        return str(enum.Name(value))  # type: ignore[attr-defined]
    except ValueError:
        return _UNKNOWN_KIND


def _kind_name(info: scip_pb2.SymbolInformation) -> str:
    return _enum_name(scip_pb2.SymbolInformation.Kind, info.kind)


def _relationship_kinds(related: scip_pb2.Relationship) -> tuple[RelationshipKind, ...]:
    flags: tuple[tuple[bool, RelationshipKind], ...] = (
        (related.is_reference, "reference"),
        (related.is_implementation, "implementation"),
        (related.is_type_definition, "type_definition"),
        (related.is_definition, "definition"),
    )
    return tuple(name for enabled, name in flags if enabled)


def _range(occurrence: scip_pb2.Occurrence) -> SourceRange | None:
    """Typed range when present, else the legacy 3 or 4 integer form; None when invalid."""
    typed = occurrence.WhichOneof("typed_range")
    if typed == "single_line_range":
        single = occurrence.single_line_range
        return _checked(single.line, single.start_character, single.line, single.end_character)
    if typed == "multi_line_range":
        multi = occurrence.multi_line_range
        return _checked(
            multi.start_line, multi.start_character, multi.end_line, multi.end_character
        )
    return _legacy(occurrence.range)


def _enclosing_range(occurrence: scip_pb2.Occurrence) -> SourceRange | None:
    typed = occurrence.WhichOneof("typed_enclosing_range")
    if typed == "single_line_enclosing_range":
        single = occurrence.single_line_enclosing_range
        return _checked(single.line, single.start_character, single.line, single.end_character)
    if typed == "multi_line_enclosing_range":
        multi = occurrence.multi_line_enclosing_range
        return _checked(
            multi.start_line, multi.start_character, multi.end_line, multi.end_character
        )
    return _legacy(occurrence.enclosing_range) if occurrence.enclosing_range else None


def _has_enclosing(occurrence: scip_pb2.Occurrence) -> bool:
    return bool(occurrence.WhichOneof("typed_enclosing_range") or occurrence.enclosing_range)


def _encloses(outer: SourceRange, inner: SourceRange) -> bool:
    return (outer.start_line, outer.start_character) <= (
        inner.start_line,
        inner.start_character,
    ) and (
        outer.end_line,
        outer.end_character,
    ) >= (inner.end_line, inner.end_character)


def _legacy(values: object) -> SourceRange | None:
    numbers = list(values)  # type: ignore[call-overload]
    if len(numbers) == 3:
        line, start, end = numbers
        return _checked(line, start, line, end)
    if len(numbers) == 4:
        return _checked(*numbers)
    return None


def _checked(
    start_line: int, start_character: int, end_line: int, end_character: int
) -> SourceRange | None:
    values = (start_line, start_character, end_line, end_character)
    if any(value < 0 for value in values):
        return None
    if (start_line, start_character) > (end_line, end_character):
        return None
    return SourceRange(*values)


class _Bounds:
    """Whether a range lies inside the document, when its text is known."""

    def __init__(self, text: str | None, encoding: int) -> None:
        # None: text unknown, structure only. "": an empty file has no valid position.
        self._lines = (
            None
            if text is None
            else [line.removesuffix("\r") for line in text.split("\n")]
            if text
            else []
        )
        self._encoding = encoding
        self._widths: dict[int, int | None] = {}

    def contains(self, located: SourceRange) -> bool:
        if self._lines is None:
            return True
        for line, character in (
            (located.start_line, located.start_character),
            (located.end_line, located.end_character),
        ):
            if line >= len(self._lines):
                return False
            width = self._width(line)
            if width is not None and character > width:
                return False
        return True

    def _width(self, line: int) -> int | None:
        """Line length in the position encoding, or None when the encoding is unspecified."""
        if line not in self._widths:
            self._widths[line] = self._measure(line)
        return self._widths[line]

    def _measure(self, line: int) -> int | None:
        assert self._lines is not None
        text = self._lines[line]
        if self._encoding == scip_pb2.UTF8CodeUnitOffsetFromLineStart:
            return len(text.encode("utf-8"))
        if self._encoding == scip_pb2.UTF16CodeUnitOffsetFromLineStart:
            return len(text.encode("utf-16-le")) // 2
        if self._encoding == scip_pb2.UTF32CodeUnitOffsetFromLineStart:
            return len(text)
        return None
